// ADDS COMPONENT TO THE PROJECT'S EDITOR STATE
export const ADD_TO_PROJECT = "ADD_TO_PROJECT";

// ADD PROJECT TO EDITOR CONTEXT
export const ADD_PROJECT = "ADD_PROJECT";

// REMOVE COMPONENT FROM PROJECT
export const REMOVE_COMPONENT = "REMOVE_COMPONENT";
